//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LapTrinhWeb.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Product_Category
    {
        public int ProId { get; set; }
        public string ProName { get; set; }
        public string ProImage { get; set; }
        public Nullable<decimal> ProPrice { get; set; }
        public Nullable<int> CatId { get; set; }
        public string CatName { get; set; }
        public string ProBreed { get; set; }
        public string ProColor { get; set; }
        public string ProAge { get; set; }
        public string ProGender { get; set; }
        public string ProVaccination { get; set; }
        public string ProDeworming { get; set; }
        public string ProHealth { get; set; }
        public string ProShipping { get; set; }
        public string Status { get; set; }
        public string Origin { get; set; }
        public Nullable<int> Quantity { get; set; }
    }
}
