//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LapTrinhWeb.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Product
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Product()
        {
            this.OrderDetails = new HashSet<OrderDetail>();
        }

        public int ProId { get; set; }

        [Display(Name = "Tên sản phẩm")]
        public string ProName { get; set; }

        [Display(Name = "Hình ảnh")]
        public string ProImage { get; set; }

        [Display(Name = "Giá")]
        public Nullable<decimal> ProPrice { get; set; }

        [Display(Name = "Danh mục")]
        public Nullable<int> CatId { get; set; }

        [Display(Name = "Giống loài")]
        public string ProBreed { get; set; }

        [Display(Name = "Màu sắc")]
        public string ProColor { get; set; }

        [Display(Name = "Tuổi")]
        public string ProAge { get; set; }

        [Display(Name = "Giới tính")]
        public string ProGender { get; set; }

        [Display(Name = "Tiêm phòng")]
        public string ProVaccination { get; set; }

        [Display(Name = "Tẩy giun")]
        public string ProDeworming { get; set; }

        [Display(Name = "Sức khỏe")]
        public string ProHealth { get; set; }

        [Display(Name = "Vận chuyển")]
        public string ProShipping { get; set; }

        [Display(Name = "Trạng thái")]
        public string Status { get; set; }

        [Display(Name = "Xuất xứ")]
        public string Origin { get; set; }

        [Display(Name = "Số lượng")]
        public Nullable<int> Quantity { get; set; }

        public virtual Category Category { get; set; }

        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OrderDetail> OrderDetails { get; set; }
    }
}
